sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# whitelist
#branches:
#  only:
#    - master
#    - develop

language: php

matrix:
  fast_finish: true

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
  - SYMFONY_VERSION="dev-master"

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer self-update && composer --version

before_script:
  - composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
